### ISSUE TITLE
formatted printing

### ISSUE THREAD

**Issue by r00tc0d3** [jwalton/gchalk#4]
Should this work?
```
fmt.Printf("colors: %-16s  %-16s %-16s\n", "default", gchalk.Yellow("yellow"), gchalk.Red("red"))
```

**Comment by jwalton** [comment]
This will not do what you think it should.  `Printf` here is going to pad the result to 16 characters, but the problem is that `Printf` doesn't take into account invisible characters.  When you call `gchalk.Red("red")`, the string it returns is `"\u001B[31mred\u001B[39m"` (where "\u001B` is the "escape" character), which is 13 characters long, so printf will only add three characters.

There are some other examples of where `fmt.Printf` is going to lead you astray.  For example, "😃" (and all emoji, most Chinese characters, and some other unicode characters) are two columns wide in the terminal, and `fmt.Printf` won't take this into account, so you'll end up with a string that's a column wider than you expect.  "👩🏻‍🚀" is a combination of multiple unicode characters joined with the "ZWJ" or ["zero-width joiner"](https://emojipedia.org/emoji-zwj-sequence/) character.  `len("👩🏻‍🚀") == 15`, and `Printf` doesn't like that at all.

I have [some code](https://github.com/jwalton/kitsch/blob/master/internal/ansigradient/tokenize.go#L28) over in [kitsch prompt](https://github.com/jwalton/kitsch) which converts an ANSI string into a set of tokens using https://github.com/jwalton/go-ansiparser, and then uses uniseg and go-runewidth to work out the `printWidth` of the string (the actual number of columns it will take up on screen).  You can use this to pad the strings yourself.  Originally I was going to put all of this into go-ansiparser, but I didn't want to drag uniseg and go-runwidth into that library if I didn't have to, as they are quite large, and I was worried someone out there would want to just parse some ANSI strings for some other reason, and wouldn't want all that bloat added into their executable.  If you're interested, I can split this out into a separate library somewhere.  Maybe something like `ansistrings` with an `ansistrings.PrintWidth(str)` and a `ansistrings.PadStart(n, str, padChar)` and `PadEnd`?

**Comment by r00tc0d3** [comment]
Thanks for the  comprehensive reply.
Yes, off course, stupid me not think of that immediately.
I worked around it by justifying/padding the strings before giving them color. This is maybe more efficient than doing it afterwards?
I will think about the proposal. Maybe I will do it myself.

**Comment by jwalton** [comment]
Doing it before hand is definitely more efficient - no need to re-parse the string in that case.
